name: Production Release

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    create-release:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            raw_tag: ${{ steps.tag_version.outputs.raw_tag  }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Bump version and push tag
              id: tag_version
              uses: Aibel365/devops-common-github-actions/generate-release-tag-action@main
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Release
              if: ${{ steps.tag_version.outputs.new_tag != '' }}
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.tag_version.outputs.raw_tag }}
                  name: Release  ${{ steps.tag_version.outputs.new_tag }}
                  generate_release_notes: true

            - name: Check Output Parameters
              if: ${{ steps.tag_version.outputs.new_tag != '' }}
              run: |
                  echo "Tag: ${{ steps.release.outputs.new_tag }}"
                  echo "Version: ${{ steps.release.outputs.new_version }}"

    # Build and deploy application to container registry
    build-deploy:
        uses: Aibel365/devops-common-github-actions/.github/workflows/docker-build-push-cached.yaml@main
        needs: create-release
        if: needs.create-release.outputs.raw_tag != ''
        with:
            repository: devops-template-react
            tags: ${{needs.create-release.outputs.raw_tag}}
            context: ./
            file: ./Dockerfile
            target: final
            hash_files_template: "**/package-lock.json"
            push: true
        secrets:
            REGISTRY_SERVER_URLS: ${{secrets.AZURE_SERVER_URLS_CONTAINER_REGISTRY}}
            REGISTRY_USERNAMES: ${{secrets.AZURE_CLINET_ID_CONTAINER_REGISTRY}}
            REGISTRY_PASSWORDS: ${{secrets.AZURE_CLIENT_SECRET_CONTAINER_REGISTRY}}
